packages:
  - 'ui'
  - 'ui-next'
  - 'common'
  - 'common-persistence'
  - 'core'
  - 'rest'
  - 'ai'
  - 'server-lite'
  - 'agent-runtime'
  - 'telemetry'
  - 'sandbox'
  - '*-persistence'
  - 'redis-*'
  - 'http-task'
  - 'json-jq-task'
  - 'workflow-event-listener'
  - 'task-status-listener'
  - 'amqp'
  - 'graph-service'
  - 'workflow-service'
  - 'knowledge-os'
