packages:
  - 'ui'
  - 'ui-next'
  - 'agent-runtime'
  - 'common'
  - 'common-persistence'
  - 'core'
  - 'rest'
  - 'ai'
  - 'server-lite'
  - 'telemetry'
  - 'sandbox'
  - 'secrets'
  - '*-persistence'
  - 'redis-*'
  - 'http-task'
  - 'json-jq-task'
  - 'kafka*'
  - 'nats*'
  - '*-storage'
  - 'workflow-event-listener'
  - 'task-status-listener'
  - 'scheduler/*'
  - 'amqp'
  - 'amqp-queue'
  - 'annotations'
  - 'graph-service'
  - 'workflow-service'
  - 'knowledge-os'
