import * as Handlebars from 'handlebars';
import * as fs from 'fs';
import * as path from 'path';
import { ProtoFile } from './proto-file';
import { AbstractMessage } from './abstract-message';

const GENERATOR_NAME = '@conductor/annotations-processor';

const FILE_TEMPLATE_SOURCE = `syntax = "proto3";
package {{protoPackageName}};

{{#includes}}
import "{{this}}";
{{/includes}}

option java_package = "{{javaPackageName}}";
option java_outer_classname = "{{javaClassName}}";
option go_package = "{{goPackageName}}";

{{#message}}
{{>message}}
{{/message}}
`;

const MESSAGE_TEMPLATE_SOURCE = `{{protoClass}} {{name}} {
{{#nested}}
    {{>message}}
{{/nested}}
{{#fields}}
    {{protoTypeDeclaration}};
{{/fields}}
}
`;

export class ProtoGen {
  private protoFiles: ProtoFile[] = [];

  constructor(
    private protoPackageName: string,
    private javaPackageName: string,
    private goPackageName: string,
  ) {}

  writeMapper(root: string, mapperPackageName: string): void {
    const lines: string[] = [];
    lines.push(`// Generated by ${GENERATOR_NAME}`);
    lines.push(`// @ts-nocheck`);
    lines.push(``);
    lines.push(`export abstract class AbstractProtoMapper {`);

    const abstractMethods = new Set<string>();

    this.protoFiles.sort((a, b) => {
      return a.getMessage().getName().localeCompare(b.getMessage().getName());
    });

    for (const protoFile of this.protoFiles) {
      const elem = protoFile.getMessage();
      const rawLines: string[] = [];
      elem.generateJavaMapper(rawLines);
      let depth = 0;
      for (const rl of rawLines) {
        const trimmed = rl.trimEnd().trimStart();
        if (trimmed.startsWith('}')) depth = Math.max(0, depth - 1);
        lines.push('  '.repeat(depth + 1) + trimmed);
        if (trimmed.endsWith('{') && !trimmed.startsWith('}')) depth++;
      }
      elem.generateAbstractMethods(abstractMethods);
    }
    for (const method of abstractMethods) {
      lines.push(`  ${method}`);
    }
    lines.push(`}`);

    const filename = path.join(root, 'AbstractProtoMapper.ts');
    console.log(`protogen: writing '${filename}'...`);
    fs.writeFileSync(filename, lines.join('\n') + '\n');
  }

  writeProtos(root: string): void {
    Handlebars.registerPartial('message', MESSAGE_TEMPLATE_SOURCE);
    const fileTemplate = Handlebars.compile(FILE_TEMPLATE_SOURCE, { noEscape: true });

    for (const file of this.protoFiles) {
      const modelDir = path.join(root, 'model');
      if (!fs.existsSync(modelDir)) {
        fs.mkdirSync(modelDir, { recursive: true });
      }
      const filename = path.join(root, file.getFilePath());
      console.log(`protogen: writing '${filename}'...`);
      const output = fileTemplate({
        protoPackageName: file.getProtoPackageName(),
        javaPackageName: file.getJavaPackageName(),
        javaClassName: file.getJavaClassName(),
        goPackageName: file.getGoPackageName(),
        includes: [...file.getIncludes()],
        message: file.getMessage().toTemplate(),
      });
      fs.writeFileSync(filename, output);
    }
  }

  processModule(modulePath: string): void {
    const mod = require(modulePath);
    for (const key of Object.keys(mod)) {
      const exported = mod[key];
      if (typeof exported === 'function') {
        try {
          const ann = Reflect.getMetadata('ProtoMessage', exported);
          if (ann !== undefined) {
            console.log(`protogen: found ${exported.name}`);
            this.protoFiles.push(
              new ProtoFile(exported, this.protoPackageName, this.javaPackageName, this.goPackageName),
            );
          }
        } catch {
          // skip non-class exports
        }
      }
    }
  }
}
