# Database persistence type.
agentmesh.db.type=postgres
agentmesh.queue.type=postgres
agentmesh.external-payload-storage.type=postgres

# Restrict the size of task execution logs. Default is set to 10.
# agentmesh.app.taskExecLogSizeLimit=10

# postgres
spring.datasource.url=jdbc:postgresql://postgresdb:5432/postgres
spring.datasource.username=agentmesh
spring.datasource.password=agentmesh

# Elastic search instance indexing is enabled.
agentmesh.indexing.enabled=true
agentmesh.indexing.type=elasticsearch
agentmesh.elasticsearch.url=http://es:9200
agentmesh.elasticsearch.indexName=agentmesh
agentmesh.elasticsearch.version=7
agentmesh.elasticsearch.clusterHealthColor=yellow

# Restrict the number of task log results that will be returned in the response. Default is set to 10.
# agentmesh.elasticsearch.taskLogResultLimit=10

# Additional modules for metrics collection exposed to Prometheus (optional)
agentmesh.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=true
