# Database persistence type.
agentmesh.db.type=mysql


# mysql
spring.datasource.url=jdbc:mysql://mysql:3306/agentmesh
spring.datasource.username=agentmesh
spring.datasource.password=agentmesh

# redis queues
agentmesh.queue.type=redis_standalone
agentmesh.redis.hosts=rs:6379:us-east-1c
agentmesh.redis-lock.serverAddress=redis://rs:6379


# Elastic search instance indexing is enabled.
agentmesh.indexing.enabled=true
agentmesh.indexing.type=elasticsearch
agentmesh.elasticsearch.url=http://es:9200
agentmesh.elasticsearch.indexName=agentmesh
agentmesh.elasticsearch.version=7
agentmesh.elasticsearch.clusterHealthColor=yellow

# Additional modules for metrics collection exposed to Prometheus (optional)
agentmesh.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=true
