# See README in the docker for configuration guide

# db.type determines the type of database used
# See various configurations below for the values
#agentmesh.db.type=SET_THIS

# =====================================================#
#              Redis Configuration Properties
# =====================================================#
#agentmesh.db.type=redis_standalone

# The last part MUST be us-east-1c, it is not used and is kept for backwards compatibility
# agentmesh.redis.hosts=rs:6379:us-east-1c
#

# agentmesh.redis-lock.serverAddress=redis://rs:6379
# agentmesh.redis.taskDefCacheRefreshInterval=1
# agentmesh.redis.workflowNamespacePrefix=agentmesh
# agentmesh.redis.queueNamespacePrefix=agentmesh_queues


# =====================================================#
#              Postgres Configuration Properties
# =====================================================#

# agentmesh.db.type=postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# Additionally you can use set the spring.datasource.XXX properties for connection pool size etc.

# If you want to use Postgres as indexing store set the following
# agentmesh.indexing.enabled=true
# agentmesh.indexing.type=postgres

# When using Elasticsearch 7 for indexing, set the following

# agentmesh.indexing.enabled=true
# agentmesh.indexing.type=elasticsearch
# agentmesh.elasticsearch.url=http://es:9200
# agentmesh.elasticsearch.version=7
# agentmesh.elasticsearch.indexName=agentmesh

# =====================================================#
#       Status Notifier Configuration Properties
# =====================================================#

# Task statuses to publish (comma-separated list)
# agentmesh.status-notifier.notification.subscribed-task-statuses=SCHEDULED,COMPLETED,FAILED,TIMED_OUT,IN_PROGRESS

# Workflow statuses to publish (comma-separated list)
# Valid values: RUNNING,COMPLETED,FAILED,TIMED_OUT,TERMINATED,PAUSED,RESUMED,RESTARTED,RETRIED,RERAN,FINALIZED
# agentmesh.status-notifier.notification.subscribed-workflow-statuses=RUNNING,COMPLETED,FAILED,TIMED_OUT,TERMINATED,PAUSED
