"""
CommitGuard GitHub issue filer: httpx POST to GitHub API (mirrors github_integration.py pattern).
No PyGithub dependency — uses the same httpx + Bearer token pattern as github_integration.py.

On CONFIRMED findings only:
  1. Sonnet 4.6 generates a fix suggestion diff.
  2. httpx files a GitHub issue with finding + PoC + fix.
  3. Returns FiledFinding with issue_url and fix_suggestion.
"""

import asyncio
import logging
import time
from typing import Optional

import httpx
try:
    from langfuse import observe
except Exception:
    def observe(name=None, **_kw):  # type: ignore[misc]
        def decorator(fn):
            return fn
        return decorator
from pydantic import BaseModel

from main import generate, MODEL_EXECUTE

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
GITHUB_HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


class FiledFinding(BaseModel):
    finding_id: str
    fix_suggestion: Optional[str]
    github_issue_url: Optional[str]
    issue_filed: bool


@observe(name="commitguard_generate_fix")
def _generate_fix(vf: dict) -> Optional[str]:
    prompt = (
        "You are a security engineer. Given this confirmed vulnerability, provide a minimal "
        "code fix as a unified diff (3-5 lines). No explanation — only the diff.\n\n"
        f"File: {vf['file']}:{vf['line']}\n"
        f"Type: {vf['vuln_type']}\n"
        f"Description: {vf['description']}\n"
    )
    try:
        raw = generate(MODEL_EXECUTE, prompt).strip()
        return raw if raw else None
    except Exception as e:
        logger.warning(f"Fix suggestion generation failed: {e}")
        return None


def _build_issue_body(vf: dict, fix_suggestion: Optional[str]) -> str:
    cvss_note = f"\n**CVSS:** {vf['cvss']}" if vf.get("cvss") else ""
    cwe_note = f"\n**CWE:** {vf['cwe']}" if vf.get("cwe") else ""
    fix_section = (
        f"\n\n## Suggested Fix\n```diff\n{fix_suggestion}\n```"
        if fix_suggestion
        else ""
    )
    return (
        f"## CommitGuard Security Finding\n\n"
        f"**Severity:** {vf['severity']}  \n"
        f"**Type:** {vf['vuln_type']}{cvss_note}{cwe_note}\n\n"
        f"## Details\n{vf['description']}\n\n"
        f"**File:** `{vf['file']}:{vf['line']}`\n\n"
        f"## Proof of Concept\n{vf['poc_summary']}"
        f"{fix_section}\n\n"
        f"---\n*Generated by CommitGuard · [Agent Mesh OS](https://github.com)*"
    )


async def _post_issue_async(owner: str, repo: str, token: str, title: str, body: str) -> dict:
    """POST to GitHub Issues API. Returns response JSON."""
    async with httpx.AsyncClient(timeout=20) as client:
        resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues",
            headers={**GITHUB_HEADERS, "Authorization": f"Bearer {token}"},
            json={"title": title, "body": body},
        )
        return {"status": resp.status_code, "data": resp.json()}


def _parse_repo_owner_name(repo_url: str) -> tuple[str, str]:
    """Extract owner and repo from https://github.com/owner/repo[.git]."""
    parts = repo_url.rstrip("/").rstrip(".git").split("/")
    return parts[-2], parts[-1]


def file_issue(vf: dict, repo_url: str, token: str) -> dict:
    """
    File a GitHub issue for a CONFIRMED finding.
    Called from CommitGuardWorkflow as a @DBOS.step().
    Returns FiledFinding dict.
    """
    fix_suggestion = _generate_fix(vf)
    owner, repo = _parse_repo_owner_name(repo_url)

    title = f"[CommitGuard] {vf['severity']}: {vf['vuln_type']} in {vf['file']}:{vf['line']}"
    body = _build_issue_body(vf, fix_suggestion)

    # Retry once on 429 with retry-after backoff
    for attempt in range(2):
        try:
            result = asyncio.run(_post_issue_async(owner, repo, token, title, body))
            status = result["status"]
            data = result["data"]

            if status == 201:
                return FiledFinding(
                    finding_id=vf["finding_id"],
                    fix_suggestion=fix_suggestion,
                    github_issue_url=data.get("html_url"),
                    issue_filed=True,
                ).model_dump()

            if status == 429 and attempt == 0:
                retry_after = int(data.get("retry_after", 60))
                logger.info(f"GitHub 429 rate limit — waiting {retry_after}s before retry")
                time.sleep(retry_after)
                continue

            logger.warning(f"GitHub issue filing failed: HTTP {status} — {data.get('message', '')}")
            return FiledFinding(
                finding_id=vf["finding_id"],
                fix_suggestion=fix_suggestion,
                github_issue_url=None,
                issue_filed=False,
            ).model_dump()

        except Exception as e:
            logger.warning(f"GitHub issue filing error: {e}")
            return FiledFinding(
                finding_id=vf["finding_id"],
                fix_suggestion=fix_suggestion,
                github_issue_url=None,
                issue_filed=False,
            ).model_dump()

    return FiledFinding(
        finding_id=vf["finding_id"],
        fix_suggestion=fix_suggestion,
        github_issue_url=None,
        issue_filed=False,
    ).model_dump()
